name: Build and push docker images
on:
  push:
    branches:
      - deploy
    paths:
      - 'AuthService/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch deploy
        uses: actions/checkout@deploy
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Build docker image
        run: docker build --platform linux/amd64 -f authservice.dockerfile -t ${{ secrets.DO_REGISTRY_NAME }}/authservice:latest .
      - name: Login to Digital Ocean
        run: doctl registry login --expiry-seconds 1200
      - name: Push docker image
        run: docker push ${{ secrets.DO_REGISTRY_NAME }}/authservice:latest
      